name: Browser Finder Test

on:
  workflow_dispatch:
    inputs:
      node_version:
        description: "Node.js version"
        required: false
        default: "20"
        type: string

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install tsx
        run: npm install -g tsx

      - name: Run test script
        run: tsx packages/browser-finder/src/puppeteer/ci.github.test.ts
        working-directory: .
