name: release
on:
  push:
    branches:
      - main

# 赋予 release-please-action 权限
permissions:
  contents: write
  pull-requests: write
jobs:
  # 设置 release-please 任务
  release-please:
    # 设置任务运行环境为 ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      # 使用 release-please-action 动作来自动创建发布 PR
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: 设置 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      # 安装所有依赖
      - name: 安装依赖
        run: pnpm install

      # 全局编译
      - name: 编译所有包
        run: pnpm run build

      # 发布 puppeteer 包
      - name: 发布 puppeteer 包
        if: ${{ steps.release.outputs['packages/puppeteer--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: packages/puppeteer
        run: pnpm run pub

      # 发布 puppeteer-core 包
      - name: 发布 puppeteer-core 包
        if: ${{ steps.release.outputs['packages/puppeteer-core--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: packages/puppeteer-core
        run: pnpm run pub

      # 发布 plugin-puppeteer 包
      - name: 发布 plugin-puppeteer 包
        if: ${{ steps.release.outputs['packages/karin-plugin-puppeteer--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: packages/karin-plugin-puppeteer
        run: pnpm run pub

      # 发布 puppeteer-server 包
      - name: 发布 puppeteer-server 包
        if: ${{ steps.release.outputs['packages/puppeteer-server--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: packages/puppeteer-server
        run: pnpm run pub
